- hosts: <ip-of-vsi>
  become: yes
  become_method: sudo
  remote_user: root 

  tasks:

  - name: Install update
    raw: apt -y update

  - name: Install Python
    raw: apt install -y python-minimal

  - name: Install Pip
    raw: apt install -y python-pip 

  - name: python3-mysqldb
    apt:
      name:
      - python-mysqldb
      state: present

  - name: python3-mysqldb
    pip:
      name:
      - PyMySQL 
      state: present 

  - name: mysql-client 
    apt: 
      name:
      - mysql-client
      - python-apt
      - python3-apt
      update_cache: yes
      state: absent 

  - name: install python-pymysql
    apt:
      pkg: mysql-server
      update_cache: yes
      state: latest
      
  - name: Update MySQL root password for localhost root account
    shell: >
      mysql -u root -NBe
      'ALTER USER "root"@"localhost"
      IDENTIFIED WITH mysql_native_password BY "Passw0rd";'

  - name: Create database user with name 'joomla' and password 'Passw0rd' with all database privileges
    mysql_user:
      name: joomla
      password: Passw0rd
      priv: '*.*:ALL'
      host: '%'
      login_user: root
      login_password: 'Passw0rd' 
      connect_timeout: 120
      state: present

  - name: Create a new database with name 'bobdata'
    mysql_db:
      name: joomla
      login_user: root
      login_password: 'Passw0rd'
      state: present

  - name: Insert
    blockinfile:
      path: /etc/mysql/my.cnf
      block: |
        [mysqld]
        bind-address    = 0.0.0.0

  - name: restart mysql service
    systemd:
      state: restarted
      name: mysql
